### PR TITLE
Change config to take subdomain and display_id as parameters

### PR DESCRIPTION
**Pull request by jlaneve**

### CODE REVIEW

**Comment by jlaneve** [comment]
@schnie - can you do a code review then merge this? should only take ~30 secs

**Comment by schnie** [comment]
@jlaneve What will happen to our old workflows that don't have this setting?  Will we have to migrate them?

**Comment by jlaneve** [comment]
talked to @benjamingregory, he said we just need to make sure everything is updated

**Comment by benjamingregory** [comment]
There's only two workflows this applies to so the change should be pretty easy.

**Pull request merged**
